window.WSID_CONFIG={
 SUPABASE_URL:"https://GANTI-PROJECT.supabase.co",
 SUPABASE_ANON_KEY:"GANTI-PUBLISHABLE-KEY",
 PANEL_NAME:"WSID SMM PANEL", OWNER_NAME:"Witama Store.ID",
 DANA_NUMBER:"ISI-NOMOR-DANA", DANA_NAME:"Witama Store.ID", QRIS_IMAGE_URL:"",
 SUPPORT_WHATSAPP:"", SUPPORT_TELEGRAM:"", SUPPORT_INSTAGRAM:""
};
