window.WSID_CONFIG={
  SUPABASE_URL:"https://hqcbunozmpjrmekszhkx.supabase.co",
  SUPABASE_ANON_KEY:"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhxY2J1bm96bXBqcm1la3N6aGt4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3OTA4ODIxODcsImV4cCI6MjEwNjQ1ODE4N30.lOBfwWGOzxZ1rh6D6jQzHitoXGV2QFRI4mzD_9SLLJ0",
  PANEL_NAME:"WSID SMM PANEL",
  OWNER_NAME:"Witama Store.ID",
  DANA_NUMBER:"ISI-NOMOR-DANA",
  DANA_NAME:"Witama Store.ID",
  QRIS_IMAGE_URL:"",
  SUPPORT_WHATSAPP:"",
  SUPPORT_TELEGRAM:"",
  SUPPORT_INSTAGRAM:""
};
